# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # # You may remove this if you don't use go modules.
    # - go mod tidy
    # # you may remove this if you don't need go generate
    # - go generate ./...
    - go mod download
    # - get -v -d ./...
builds:
  - env:
    - CGO_ENABLED=0
    binary: k3ctl
    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386, amd64 and arm64.
    goarch:
      - amd64
      - arm64
      # - arm
    # GOARM to build for when GOARCH is arm.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Default is only 6.
    # goarm:
    #   - '6'
    #   - '7'
    # GOAMD64 to build when GOARCH is amd64.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Default is only v1.
    # goamd64:
    #   - v2
    #   - v3
    goos:
      - linux
      - darwin
      # - windows
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    # Default is empty.
    ignore:
      - goos: darwin
        goarch: '386'
      # - goos: linux
      #   goarch: arm
      #   goarm: '7'
      # - goarm: mips64
      # - gomips: hardfloat
      # - goamd64: v4
    # targets:
    #   - linux_amd64
    #   - linux_arm64
    #   - linux_ppc64le
    #   - darwin_amd64
    #   - darwin_arm64
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - "-s -w -X github.com/grengojbo/k3ctl/cmd/version.Version={{.Version}} -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser"
    #   - ./usemsan=-msan
archives:
  - 
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}"
    format: binary
    # replacements:
    #   darwin: Darwin
    #   linux: Linux
    #   windows: Windows
    #   386: i386
    #   amd64: x86_64
    # Can be used to change the archive formats for specific GOOSs.
    # Most common use case is to archive as zip on Windows.
    # Default is empty.
    # format_overrides:
    #   - goos: windows
    #     format: zip
checksum:
  name_template: 'checksums.txt'
# snapshot:
#   name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
